// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1DSync.Data;

namespace _1DSync.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190217185426_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("_1DSync.Models.PseudoDynamicEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("HEX(RANDOMBLOB(16))");

                    b.Property<DateTime>("DateTimeCol1");

                    b.Property<DateTime>("DateTimeCol2");

                    b.Property<double>("DoubleCol1");

                    b.Property<double>("DoubleCol2");

                    b.Property<double>("DoubleCol3");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("StringCol1");

                    b.Property<string>("StringCol2");

                    b.Property<string>("StringCol3");

                    b.Property<string>("StringCol4");

                    b.Property<string>("StringCol5");

                    b.Property<string>("StringCol6");

                    b.Property<string>("StringCol7");

                    b.Property<string>("StringCol8");

                    b.Property<string>("StringCol9");

                    b.Property<bool>("SyncStatus");

                    b.HasKey("Id");

                    b.ToTable("PseudoDynamicEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
